services:
  airport:
    build:
      context: .
    ports:
      - "8000:8000"
    env_file:
      - .env
    environment:
      - ENVIRONMENT=docker
    depends_on:
      - redis
      - db
    networks:
      - default
    command: >
      sh -c "python manage.py migrate &&
      python manage.py loaddata airport_initial_data.json
      && python manage.py runserver 0.0.0.0:8000"

  db:
    image: postgres:16-alpine
    restart: always
    env_file:
      - .env
    ports:
      - "5432:5432"
    volumes:
      - my_db:/var/lib/postgresql/data

  redis:
    image: redis:latest
    ports:
      - "6380:6379"
    networks:
      - default

networks:
  default:
    name: api-airport-network

volumes:
  my_db:
